### ISSUE TITLE
cheat rdebug throws exception

### ISSUE THREAD

**Issue by sheerun** [defunkt/cheat#11]
```
✗ cheat rdebug
/Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): mapping values are not allowed in this context at line 1 column 161 (Psych::SyntaxError)
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/psych.rb:151:in `parse'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/psych.rb:127:in `load'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/cheat-1.3.1/lib/cheat.rb:129:in `show'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/cheat-1.3.1/lib/cheat.rb:37:in `block in fetch_sheet'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/open-uri.rb:150:in `open_uri'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/open-uri.rb:677:in `open'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/1.9.1/open-uri.rb:33:in `open'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/cheat-1.3.1/lib/cheat.rb:33:in `fetch_sheet'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/cheat-1.3.1/lib/cheat.rb:29:in `sheets'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/lib/ruby/gems/1.9.1/gems/cheat-1.3.1/bin/cheat:10:in `<top (required)>'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/bin/cheat:23:in `load'
    from /Users/sheerun/.rbenv/versions/1.9.3-p194-perf/bin/cheat:23:in `<main>'
```

**Comment by sferik** [comment]
This appears to be a bug in the server, not in the client. If you look at your ~/.cheat directory, you'll notice the files it's downloading are HTML (they should be YAML). @amateurhuman and I are working on fixing this server problem now, so I'm going to close this issue.
