### ISSUE TITLE
Error running cheat

### ISSUE THREAD

**Issue by yrammos** [defunkt/cheat#12]
I get the following error running `cheat` on RVM-based Ruby 1.9.3p286. Any ideas?

Thanks!

```
/Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): mapping values are not allowed in this context at line 1 column 161 (Psych::SyntaxError)
        from /Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
        from /Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych.rb:151:in `parse'
        from /Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/psych.rb:127:in `load'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/gems/cheat-1.3.2/lib/cheat.rb:133:in `show'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/gems/cheat-1.3.2/lib/cheat.rb:128:in `process'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/gems/cheat-1.3.2/lib/cheat.rb:28:in `block in sheets'
        from /Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:150:in `open_uri'
        from /Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:677:in `open'
        from /Users/rammos/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/open-uri.rb:33:in `open'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/gems/cheat-1.3.2/lib/cheat.rb:28:in `sheets'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/gems/cheat-1.3.2/bin/cheat:10:in `<top (required)>'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/bin/cheat:19:in `load'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/bin/cheat:19:in `<main>'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/bin/ruby_noexec_wrapper:14:in `eval'
        from /Users/rammos/.rvm/gems/ruby-1.9.3-p286@global/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by midwire** [comment]
Same problem here.  It appears to be pulling HTML cheat sheets but tries to parse them as YAML.

**Comment by patricklewis** [comment]
Same problem on Ruby 1.9.3p286 via rbenv.

**Comment by sferik** [comment]
Hi all,

I just started maintaining this project less than a week ago. This is a known issue caused by a botched Heroku migration. We are in the process of rewriting the server-side of the app using modern, well-maintained tools. The existing app was built using Camping, Mongrel, Active Record 2.1. The new app is built using Sinatra, Puma, and ActiveRecord 3. You can test the new app by pointing your client at http://sferik-cheat.heroku.com/. I hope to get this app deployed to the production endpoint some time this weekend.

Thanks for your patience.

**Comment by yrammos** [comment]
Sounds great, thanks for your work.

**Comment by sferik** [comment]
Try downloading the latest version. You may need to clear your cache at `~/.cheat`.

**Comment by yrammos** [comment]
Confirming it works here, thanks!
